# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

################################################################
# Set the basic box to be provisioned
################################################################
  config.vm.box = "minimal/centos7"

################################################################
# Specify a local folder to share with the VMs
################################################################
  config.vm.synced_folder ".", "/vagrant", disabled: false

################################################################
# Provision machines via Libvirt toolkit.
################################################################
  config.vm.provider "virtualbox" do |vb|
    vb.name = "shibboleth"
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.memory = 1024
  end

################################################################
# Vagrant's "change host name" sets the short host name.
# Reset /etc/hostname to the *full* host name
################################################################
  config.vm.provision "shell",
    inline: "hostname --fqdn > /etc/hostname && hostname -F /etc/hostname"

################################################################
# Vagrant's "change host name" capability for Fedora maps hostname
# to loopback.  We must repair /etc/hosts
################################################################
  config.vm.provision "shell",
    inline: "sed -ri 's/127\.0\.0\.1\s.*/127.0.0.1 localhost localhost.localdomain/' /etc/hosts"

################################################################
# Configure the Shibboleth server
################################################################
  config.vm.define "Shibboleth" do |shibboleth|
    shibboleth.vm.network "private_network", ip: "192.168.45.10"
    shibboleth.vm.hostname = "shibboleth.billFarber.local"
  end

################################################################
# Configure the marktom server.
# This server will run both MarkLogic and Tomcat.
################################################################
#  config.vm.define "marktom" do |marktom|
#    marktom.vm.network "private_network", ip: "192.168.35.20"
#    marktom.vm.hostname = "marktom.bigtop.local"
#  end

################################################################
# Configure the client VM which will run GNOME
################################################################
#  config.vm.define "client" do |client|
#    client.vm.network "private_network", ip: "192.168.35.30"
#    client.vm.hostname = "client.bigtop.local"
#  end

end
